"""
Trading Autopilot — AI Decision Engine.

The core intelligence that processes news, portfolio state, and market data
to generate actionable trade ideas. Integrates with Grok AI for analysis
and the safety system for validation.
"""

from __future__ import annotations

import json
from typing import Optional

from loguru import logger
from openai import OpenAI

from backend.ai.prompts import trade_idea_prompt, risk_assessment_prompt
from backend.config import get_settings
from backend.data.models import TradeIdea, OrderSide
from backend.risk.position_sizer import get_position_sizer
from backend.risk.safety_layers import get_safety_layers, TradeProposal
from backend.risk.correlation import get_sector
from backend.trading.paper_trader import get_paper_trader


class DecisionEngine:
    """
    AI-powered trade decision engine.

    Pipeline:
    1. Gather context (portfolio, news, market data)
    2. Generate trade ideas via Grok AI
    3. Validate each idea through the 7-layer safety system
    4. Size positions using Kelly Criterion
    5. Return only approved, sized trade recommendations
    """

    def __init__(self) -> None:
        self._settings = get_settings()
        self._grok_client: Optional[OpenAI] = None

    def _get_grok_client(self) -> OpenAI:
        """Lazy-initialize the Grok API client."""
        if self._grok_client is None:
            self._grok_client = OpenAI(
                api_key=self._settings.grok_api_key,
                base_url=self._settings.grok_base_url,
            )
        return self._grok_client

    async def generate_trade_ideas(
        self,
        news_analyses: list[dict],
        market_context: str = "",
    ) -> list[dict]:
        """
        Generate trade ideas from current context.

        Steps:
        1. Get portfolio state
        2. Send context to Grok AI
        3. Parse AI response into trade ideas
        4. Validate each through safety layers
        5. Size positions with Kelly Criterion
        6. Return approved ideas

        Returns:
            List of validated, sized trade ideas.
        """
        trader = get_paper_trader()
        portfolio = trader.get_portfolio_summary()

        # ── Build risk parameters ──────────────────────────────────
        risk_params = {
            "max_risk_pct": self._settings.max_risk_per_trade_pct,
            "max_position_pct": self._settings.max_single_position_pct,
            "max_positions": self._settings.max_positions,
            "current_positions": trader.positions_count,
        }

        # ── Get AI trade ideas ─────────────────────────────────────
        prompt = trade_idea_prompt(
            portfolio_summary=portfolio,
            news_analyses=news_analyses,
            market_context=market_context,
            risk_params=risk_params,
        )

        raw_ideas = await self._call_grok(prompt)
        if not raw_ideas:
            logger.info("No trade ideas generated by AI")
            return []

        # ── Validate and size each idea ────────────────────────────
        approved_ideas: list[dict] = []
        safety = get_safety_layers()
        sizer = get_position_sizer()

        for idea in raw_ideas:
            try:
                symbol = idea.get("symbol", "")
                if not symbol:
                    continue

                # Create a trade proposal for safety check
                proposal = TradeProposal(
                    symbol=symbol,
                    side=idea.get("side", "BUY"),
                    quantity=1,  # Will be sized after safety check
                    price=idea.get("suggested_entry", 0),
                    sector=idea.get("sector", get_sector(symbol)),
                    ai_confidence=idea.get("confidence", 0),
                    news_sources=len(idea.get("news_catalysts", [])),
                )

                # Run through safety layers
                risk_result = safety.check_all(proposal)

                if not risk_result.passed:
                    logger.info(
                        f"Trade idea {symbol} blocked: {risk_result.blocked_by}"
                    )
                    idea["status"] = "blocked"
                    idea["blocked_by"] = risk_result.blocked_by
                    continue

                # Size the position with Kelly Criterion
                entry = idea.get("suggested_entry", 0)
                sl = idea.get("stop_loss", entry * 0.95)
                tp = idea.get("take_profit", entry * 1.10)
                win_prob = idea.get("confidence", 50) / 100

                sizing = sizer.calculate_position_size(
                    symbol=symbol,
                    entry_price=entry,
                    stop_loss=sl,
                    take_profit=tp,
                    win_probability=win_prob,
                )

                idea["position_size"] = sizing["quantity"]
                idea["kelly_fraction"] = sizing["kelly_fraction"]
                idea["actual_risk"] = sizing["actual_risk_amount"]
                idea["status"] = "approved"
                idea["risk_warnings"] = risk_result.warnings

                if sizing["quantity"] > 0:
                    approved_ideas.append(idea)
                    logger.info(
                        f"Trade idea approved: {idea['side']} "
                        f"{sizing['quantity']}x {symbol} "
                        f"@ ₹{entry:.2f} (confidence: {idea['confidence']:.0f}%)"
                    )

            except Exception as exc:
                logger.error(f"Error processing trade idea: {exc}")
                continue

        logger.info(
            f"Decision engine: {len(raw_ideas)} ideas generated, "
            f"{len(approved_ideas)} approved"
        )
        return approved_ideas

    async def assess_risk(
        self,
        symbol: str,
        side: str,
        price: float,
    ) -> dict:
        """
        Get an AI risk assessment for a specific trade.

        Returns risk score, recommendation, and concerns.
        """
        trader = get_paper_trader()
        positions = trader.get_all_positions()
        performance = trader.get_performance_metrics()

        prompt = risk_assessment_prompt(
            trade_symbol=symbol,
            trade_side=side,
            trade_price=price,
            portfolio_positions=positions,
            recent_performance=performance,
        )

        try:
            result = await self._call_grok(prompt)
            if isinstance(result, dict):
                return result
            return {"risk_score": 50, "recommendation": "caution", "concerns": []}
        except Exception as exc:
            logger.error(f"Risk assessment failed: {exc}")
            return {"risk_score": 50, "recommendation": "caution", "concerns": [str(exc)]}

    async def _call_grok(self, prompt: str) -> list | dict | None:
        """
        Call Grok AI and parse JSON response.

        Returns parsed JSON (list or dict) or None on failure.
        """
        try:
            client = self._get_grok_client()
            response = client.chat.completions.create(
                model=self._settings.grok_model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are an expert financial trading AI. "
                            "Always respond with valid JSON only. "
                            "No markdown, no explanations, just JSON."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.4,
                max_tokens=1500,
            )

            raw_text = response.choices[0].message.content.strip()

            # Strip markdown code blocks if present
            if "```json" in raw_text:
                raw_text = raw_text.split("```json")[1].split("```")[0]
            elif "```" in raw_text:
                raw_text = raw_text.split("```")[1].split("```")[0]

            return json.loads(raw_text.strip())

        except json.JSONDecodeError as exc:
            logger.error(f"Failed to parse Grok response: {exc}")
            return None
        except Exception as exc:
            logger.error(f"Grok API call failed: {exc}")
            return None


# ── Module-level singleton ─────────────────────────────────────────

_engine: DecisionEngine | None = None


def get_decision_engine() -> DecisionEngine:
    """Return the global DecisionEngine singleton."""
    global _engine
    if _engine is None:
        _engine = DecisionEngine()
    return _engine
